# -*- coding: utf-8 -*-
"""dashboardEdge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mb5H6_mJ8IBqIzwnywJNfGKK-qyJVeAM

# 📊 Dashboard FIWARE — Luminosidade, Umidade e Temperatura

Consulta o **STH-Comet** e gera gráficos interativos para os três sensores da **lamp001**:
- 💡 Luminosidade (`l` → `luminosity`)
- 💧 Umidade (`u` → `humidity`)
- 🌡️ Temperatura (`t` → `temperature`)

---
**Pré-requisito:** FIWARE rodando, dispositivo `lamp001` provisionado e STH-Comet com subscrição ativa.
"""

!pip install requests matplotlib -q

"""## ⚙️ Configurações"""

# =============================================================
# CONFIGURAÇÕES — edite conforme o seu ambiente
# =============================================================

# ✅ CORRIGIDO: era "http//..." (faltava ':'), agora "http://..."
BASE_URL = "http://34.170.247.140"   # IP do servidor FIWARE (Orion/STH)
STH_PORT = 8666

# ✅ CORRIGIDO: era Lamp:002 — agora bate com o device_id do Postman e do .ino
ENTITY_TYPE = "Lamp"
ENTITY_ID   = "urn:ngsi-ld:Lamp:001"

FIWARE_SERVICE     = "smart"
FIWARE_SERVICEPATH = "/"

# Atributos — nome exato como registrado no IoT Agent
# object_id no .ino:  l → luminosity | u → humidity | t → temperature
ATRIBUTOS = {
    "luminosity" : {"label": "Luminosidade", "unidade": "lux", "cor": "#f39c12", "emoji": "💡"},
    "humidity"   : {"label": "Umidade",       "unidade": "%",   "cor": "#2980b9", "emoji": "💧"},
    "temperature": {"label": "Temperatura",   "unidade": "°C",  "cor": "#e74c3c", "emoji": "🌡️"},
}

print("✅ Configurações carregadas!")
print(f"   Servidor : {BASE_URL}:{STH_PORT}")
print(f"   Entidade : {ENTITY_ID} ({ENTITY_TYPE})")

"""## 🔌 Funções de coleta"""

import requests
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timezone

def obter_dados_atributo(atributo: str, lastN: int) -> list:
    url = (
        f"{BASE_URL}:{STH_PORT}/STH/v1/contextEntities"
        f"/type/{ENTITY_TYPE}/id/{ENTITY_ID}"
        f"/attributes/{atributo}?lastN={lastN}"
    )
    headers = {
        "fiware-service":     FIWARE_SERVICE,
        "fiware-servicepath": FIWARE_SERVICEPATH,
    }
    try:
        resp = requests.get(url, headers=headers, timeout=10)
        if resp.status_code == 200:
            data = resp.json()
            # Caminho seguro para os valores
            try:
                return data["contextResponses"][0]["contextElement"]["attributes"][0]["values"]
            except (KeyError, IndexError):
                print(f"⚠️  [{atributo}] Resposta inesperada: {data}")
                return []
        else:
            print(f"⚠️  [{atributo}] HTTP {resp.status_code}: {resp.text[:300]}")
            return []
    except requests.exceptions.ConnectionError:
        print(f"❌ [{atributo}] Sem conexão com {BASE_URL}:{STH_PORT}")
        return []
    except Exception as e:
        print(f"❌ [{atributo}] Erro: {e}")
        return []


def parsear_dados(registros: list):
    valores, tempos = [], []
    for r in registros:
        try:
            t_str = r["recvTime"].replace("Z", "+00:00")
            tempos.append(datetime.fromisoformat(t_str))
            valores.append(float(r["attrValue"]))
        except Exception:
            pass
    return tempos, valores


print("✅ Funções definidas!")

"""## 📥 Coletar dados"""

# Número de leituras a buscar por sensor
lastN = 30   # ← altere aqui se quiser (1–1000)

print(f"🔍 Buscando os últimos {lastN} registros...\n")

dados_coletados = {}
for attr, info in ATRIBUTOS.items():
    registros = obter_dados_atributo(attr, lastN)
    tempos, valores = parsear_dados(registros)
    dados_coletados[attr] = {"tempos": tempos, "valores": valores}
    status = f"{len(valores)} pontos" if valores else "⚠️ sem dados"
    print(f"  {info['emoji']} {info['label']:<14}: {status}")

total = sum(len(d['valores']) for d in dados_coletados.values())
print(f"\n✅ Total de pontos coletados: {total}")

if total == 0:
    print()
    print("💡 DICA — Se todos os sensores retornaram 'sem dados', verifique:")
    print("   1. BASE_URL está correta e acessível?")
    print("   2. A subscrição STH-Comet foi criada no Postman (pasta STH-Comet > step 2)?")
    print("   3. O dispositivo lamp001 já enviou dados pelo MQTT?")
    print(f"   4. A entidade existe? Teste: {BASE_URL}:1026/v2/entities/{ENTITY_ID}")

"""## 📊 Dashboard"""

fig, axes = plt.subplots(3, 1, figsize=(14, 12), sharex=False)
fig.suptitle("📊 Dashboard FIWARE — lamp001", fontsize=16, fontweight="bold", y=0.99)

for ax, (attr, info) in zip(axes, ATRIBUTOS.items()):
    tempos  = dados_coletados[attr]["tempos"]
    valores = dados_coletados[attr]["valores"]

    ax.set_title(f"{info['emoji']} {info['label']} ({info['unidade']})", fontsize=13)

    if not valores:
        ax.text(0.5, 0.5, "Sem dados disponíveis",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=13, color="gray")
        continue

    media  = sum(valores) / len(valores)
    minimo = min(valores)
    maximo = max(valores)

    ax.plot(tempos, valores, marker="o", markersize=4, linewidth=1.5,
            color=info["cor"], label="Leituras")
    ax.fill_between(tempos, valores, alpha=0.12, color=info["cor"])
    ax.axhline(media, color="gray", linestyle="--", linewidth=1.2,
               label=f"Média: {media:.2f} {info['unidade']}")

    idx_min = valores.index(minimo)
    idx_max = valores.index(maximo)
    ax.annotate(f"Mín: {minimo:.1f}", xy=(tempos[idx_min], minimo),
                xytext=(10, -18), textcoords="offset points", fontsize=8, color="#555",
                arrowprops=dict(arrowstyle="->", color="#aaa", lw=0.8))
    ax.annotate(f"Máx: {maximo:.1f}", xy=(tempos[idx_max], maximo),
                xytext=(10, 8),  textcoords="offset points", fontsize=8, color="#555",
                arrowprops=dict(arrowstyle="->", color="#aaa", lw=0.8))

    ax.set_ylabel(info["unidade"], fontsize=11)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M\n%d/%m"))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax.tick_params(axis="x", rotation=30, labelsize=8)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend(fontsize=9, loc="upper right")

    stats = f"n={len(valores)}  |  Mín={minimo:.2f}  |  Méd={media:.2f}  |  Máx={maximo:.2f}"
    ax.text(0.01, 0.03, stats, transform=ax.transAxes, fontsize=8, color="#444",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.7))

plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig("dashboard_fiware.png", dpi=150, bbox_inches="tight")
plt.show()
print("💾 Salvo como dashboard_fiware.png")

"""## 📋 Resumo estatístico"""

print(f"{'Sensor':<18} {'Leituras':>10} {'Mínimo':>10} {'Média':>10} {'Máximo':>10} {'Unidade':>8}")
print("-" * 68)
for attr, info in ATRIBUTOS.items():
    valores = dados_coletados[attr]["valores"]
    nome = info['emoji'] + ' ' + info['label']
    if valores:
        media  = sum(valores) / len(valores)
        print(f"{nome:<18} {len(valores):>10} {min(valores):>10.2f} {media:>10.2f} {max(valores):>10.2f} {info['unidade']:>8}")
    else:
        print(f"{nome:<18} {'—':>10} {'—':>10} {'—':>10} {'—':>10} {info['unidade']:>8}")